feat: tries to add exclusiveMaximum and exclusiveMinimum
causes the following issue when render script is called

Rendering SVG diagrams...
> visualization/td.svg
> visualization/hctl.svg
Error: syntax error in line 1
... <font color="#c83500" face="mono"></font> ...
in label of node IntegerSchema
Error: syntax error in line 1
... <font color="#c83500" face="mono"></font> ...
in label of node NumberSchema
> visualization/jsonschema.svg
> visualization/wotsec.svg